# Generated by Django 4.0.6 on 2022-08-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamilia', '0006_alter_herramientas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramientas',
            name='disponible',
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herramientas',
            name='tipo_de_tarea',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='dia_de_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tareas',
            name='responsable',
            field=models.CharField(max_length=30),
        ),
    ]
